[package]
name = "via-spike-townfabric"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
via-artifact = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
